name: CI
on: [push]
jobs:
  qual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npx react-scripts test --watchAll=false
